// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6sTxs_9xMnmaGiitQPRTU4rmpqyaCuOc',
    appId: '1:1001396699067:web:88533439f9ffb4db514e9e',
    messagingSenderId: '1001396699067',
    projectId: 'walchand-7acb0',
    authDomain: 'walchand-7acb0.firebaseapp.com',
    storageBucket: 'walchand-7acb0.firebasestorage.app',
    measurementId: 'G-RKKEZ40161',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQbyiJERQzztkiu-aY7sj8tuBoFJIDAhc',
    appId: '1:1001396699067:android:96ea1440e11da699514e9e',
    messagingSenderId: '1001396699067',
    projectId: 'walchand-7acb0',
    storageBucket: 'walchand-7acb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_z1ntlEtyVueeRYSGOpkoLuQc3wwkD5Y',
    appId: '1:1001396699067:ios:94940483545a774d514e9e',
    messagingSenderId: '1001396699067',
    projectId: 'walchand-7acb0',
    storageBucket: 'walchand-7acb0.firebasestorage.app',
    iosBundleId: 'com.example.readease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_z1ntlEtyVueeRYSGOpkoLuQc3wwkD5Y',
    appId: '1:1001396699067:ios:94940483545a774d514e9e',
    messagingSenderId: '1001396699067',
    projectId: 'walchand-7acb0',
    storageBucket: 'walchand-7acb0.firebasestorage.app',
    iosBundleId: 'com.example.readease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6sTxs_9xMnmaGiitQPRTU4rmpqyaCuOc',
    appId: '1:1001396699067:web:be8e9e5bdd8c48b5514e9e',
    messagingSenderId: '1001396699067',
    projectId: 'walchand-7acb0',
    authDomain: 'walchand-7acb0.firebaseapp.com',
    storageBucket: 'walchand-7acb0.firebasestorage.app',
    measurementId: 'G-5FBQVNV5G5',
  );
}
